title: GENIUS Lab Deadlines
description: Countdowns to AI, CV, Mobile System, and Medical Conferences
author: Hongfei Xue

domain: "genius-lab-deadlines.github.io"
baseurl: ""

github_username: genius-lab-deadlines
github_repo: genius-lab-deadlines

markdown: markdown

